spring:
  application:
    name: boot-study
  profiles:
    active: local

upload:
  path: C:/upload
  max-size: 10MB
  allowed-types:
    - image/png
    - image/jpeg

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/bootstudy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: bootuser
    password: bootpass1234
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true

server:
  port: 8081

upload:
  path: C:/upload/local

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: ${SERVER_PORT:8080}
